#!/bin/bash

export PKG_CONFIG_PATH=/opt/xserver-xir-install/lib/pkgconfig:${PKG_CONFIG_PATH}
export LD_LIBRARY_PATH=/opt/xserver-xir-install/lib/:${LD_LIBRARY_PATH}
export LD_RUN_PATH=/opt/xserver-xir-install/lib/:${LD_RUN_PATH}
export BUILD_GLOBAL=true
make
make install
